services:

    Intervention\Image\ImageManager:
        class: Intervention\Image\ImageManager

    League\Glide\Manipulators\Crop:
        class: League\Glide\Manipulators\Crop

    League\Glide\Manipulators\Size:
        class: League\Glide\Manipulators\Size
        arguments: [ 4000000 ]

    League\Glide\Manipulators\Encode:
        class: League\Glide\Manipulators\Encode

    League\Glide\Api\Api:
        class: League\Glide\Api\Api
        arguments:
            - '@Intervention\Image\ImageManager'
            -
                - '@League\Glide\Manipulators\Crop'
                - '@League\Glide\Manipulators\Size'
                - '@League\Glide\Manipulators\Encode'

    League\Glide\Responses\SymfonyResponseFactory:
        class: League\Glide\Responses\SymfonyResponseFactory
