# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
parameters:
    photoDirectoryPath: '%env(resolve:SOURCE_DIR)%'
    cacheDirectoryPath: "%kernel.root_dir%/../var/img_cache"
    showDirectoryPath: '%env(resolve:SLIDE_SHOW_DIR)%'

oneup_flysystem:
    adapters:
        photos_adapter:
            local:
                directory: '%photoDirectoryPath%'
        cache_adapter:
            local:
                directory: '%cacheDirectoryPath%'
        slideshow_adapter:
            local:
                directory: '%showDirectoryPath%'
        pseudocache_adapter:
            memory: ~

    filesystems:
        photos_filesystem:
            adapter: photos_adapter
            alias: photos_filesystem
        cache_filesystem:
            adapter: cache_adapter
            alias: cache_filesystem
        slideshow_filesystem:
            adapter: slideshow_adapter
            alias: slideshow_filesystem
        pseudocache_filesystem:
            adapter: pseudocache_adapter
            alias: pseudocache_filesystem
