<?php
/**
 * DirectoryApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Slideshow manager
 *
 * API for Slideshow manager SPA
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Api\Model\Error;
use Api\Model\ListDirectoryInfoResponse;
use Api\Model\ListDirectoryTreeResponse;

/**
 * DirectoryApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface DirectoryApiInterface
{

    /**
     * Operation listDirectory
     *
     * Directory contents
     *
     * @param  string $id   (required)
     * @param  int $page   (optional)
     * @param  int $limit   (optional)
     * @param  string $sort   (optional)
     * @param  string $dir   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \Api\Model\ListDirectoryInfoResponse
     *
     */
    public function listDirectory(string $id, int $page = null, int $limit = null, string $sort = null, string $dir = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation listDirectoryTree
     *
     * Directory tree
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \Api\Model\ListDirectoryTreeResponse
     *
     */
    public function listDirectoryTree(&$responseCode, array &$responseHeaders);
}
